strategy:
  matrix:
    linux:
      imageName: 'linux'
    mac:
      imageName: 'Darwin'
    windows:
      imageName: 'Windows_NT'

pool:
  name: BlueQuartz Self Hosted
  demands:
    - Agent.Os -equals $(imageName)

workspace:
  clean: all

variables:
  dream3d_source_dir: $(Build.Repository.LocalPath)/Workspace/DREAM3D
  ci_build_dir: $(Build.Repository.LocalPath)/Build
  d3d_data_dir: $(Build.Repository.LocalPath)/Workspace/DREAM3D_Data

steps:
- script: |
    echo System.PullRequest.SourceBranch=$(System.PullRequest.SourceBranch)
    echo System.PullRequest.PullRequestNumber=$(System.PullRequest.PullRequestNumber)
    echo Build.SourceBranchName=$(Build.SourceBranchName)
    echo Build.Repository.Name=$(Build.Repository.Name)
    echo Build.Repository.Uri=$(Build.Repository.Uri)
    echo Agent.WorkFolder=$(Agent.WorkFolder)
    echo Agent.os=$(Agent.os)
    echo Build.BuildNumber=$(Build.BuildNumber)
  displayName: 'Dump Azure Variables'

- script: |
    $(CMake) -G Ninja -S $(Build.Repository.LocalPath) -B $(ci_build_dir)
    $(CMake) --build $(ci_build_dir)
  displayName: Clone Repositories

- script: |
    cd $(d3d_data_dir)
    $(CMake) -E tar xv SmallIN100.tar.gz
    $(CMake) -E tar xv T12-MAI-2010.tar.gz
    $(CMake) -E tar xv Image.tar.gz
  displayName: Extracting Data Archives

- script: |
    $(CMake) -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DDREAM3D_SDK:PATH=$(Agent.WorkFolder) -DDREAM3D_DATA_DIR:PATH=$(d3d_data_dir) -DBUILDNAME:STRING="$(Agent.MachineName)-$(Agent.OS)-$(Build.SourceBranchName)_$(Build.BuildNumber)" $(dream3d_source_dir)
  displayName: Configure DREAM3D

- script: |
    $(CMake) --build $(Build.BinariesDirectory) --config Release --target all
  displayName: Build DREAM3D

- script: |
    cd $(Build.BinariesDirectory)
    $(CTest) -C Release -D Experimental --timeout 7200 -DCTEST_SITE:STRING=$(Agent.MachineName).bluequartz.net -Ddashboard_source_name:STRING=DREAM3D
  displayName: Testing DREAM3D

- task: PublishTestResults@2
  inputs:
    testResultsFormat: CTest
    testResultsFiles: $(Build.BinariesDirectory)/Testing/*/Test.xml

- script: |
    cd $(Build.BinariesDirectory)
    $(CPack) -C Release -V
  displayName: Packing DREAM3D
