jobs:
- job:
  strategy:
    matrix:
      macOS:
        imageName: Darwin
      Windows:
        imageName: Windows_NT
      Linux:
        imageName: Linux

  pool:
    name: BlueQuartz Self Hosted
    demands:
      - Agent.OS -equals $(imageName)
      - BQ.ExperimentalBuild

  workspace:
    clean: all

  timeoutInMinutes: 120

  variables:
    dream3d_source_dir: $(Build.Repository.LocalPath)/Workspace/DREAM3D
    ci_build_dir: $(Build.Repository.LocalPath)/Build
    d3d_data_dir: $(Build.Repository.LocalPath)/Workspace/DREAM3D_Data
    build_type: Release

  steps:
  - script: |
      echo System.PullRequest.SourceBranch=$(System.PullRequest.SourceBranch)
      echo System.PullRequest.PullRequestNumber=$(System.PullRequest.PullRequestNumber)
      echo Build.SourceBranchName=$(Build.SourceBranchName)
      echo Build.Repository.Name=$(Build.Repository.Name)
      echo Build.Repository.Uri=$(Build.Repository.Uri)
      echo Agent.WorkFolder=$(Agent.WorkFolder)
      echo Agent.OS=$(Agent.OS)
      echo Build.BuildNumber=$(Build.BuildNumber)
    displayName: 'Dump Azure Variables'

  - script: |
      cmake -G Ninja -S $(Build.Repository.LocalPath) -B $(ci_build_dir)
      cmake --build $(ci_build_dir)
    displayName: Clone Repositories

  - script: |
      cd $(d3d_data_dir)/Data
      cmake -E tar xv SmallIN100.tar.gz
      cmake -E tar xv T12-MAI-2010.tar.gz
      cmake -E tar xv Image.tar.gz
    displayName: Extracting Data Archives

  - script: |
      cmake -S $(dream3d_source_dir) -B $(Build.BinariesDirectory) -G Ninja -DCMAKE_BUILD_TYPE:STRING=$(build_type) -DDREAM3D_SDK:PATH=$(Agent.WorkFolder) -DDREAM3D_DATA_DIR:PATH=$(d3d_data_dir) -DBUILDNAME:STRING="$(Agent.MachineName)-$(Agent.OS)-$(Build.SourceBranchName)_$(Build.BuildNumber)" -DSIMPL_EMBED_PYTHON:BOOL=ON
    displayName: Configure DREAM3D

  - script: |
      cmake --build $(Build.BinariesDirectory) --config $(build_type) --target all
    displayName: Build DREAM3D

  - script: |
      cd $(Build.BinariesDirectory)
      ctest -C $(build_type) -D Experimental --timeout 7200 -DCTEST_SITE:STRING=$(Agent.MachineName).bluequartz.net -Ddashboard_source_name:STRING=DREAM3D
    continueOnError: true
    displayName: Testing DREAM3D

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: CTest
      testResultsFiles: $(Build.BinariesDirectory)/Testing/*/Test.xml
      testRunTitle: CTest_$(Agent.Name)_$(Agent.OS)
      failTaskOnFailedTests: true
    displayName: Publish Test Results

  - script: |
      cd $(Build.BinariesDirectory)
      cpack -C $(build_type) -V
    displayName: Packing DREAM3D
