# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
stages:
- stage: Build
  jobs:
  - job: macOS
    pool:
      name: BlueQuartz Self Hosted
    steps:
    - script: |
        echo System.PullRequest.SourceBranch=$(System.PullRequest.SourceBranch)
        echo System.PullRequest.PullRequestNumber=$(System.PullRequest.PullRequestNumber)
        echo Build.SourceBranchName=$(Build.SourceBranchName)
        echo Build.Repository.Name=$(Build.Repository.Name)
        echo Build.Repository.Uri=$(Build.Repository.Uri)
      displayName: 'Dump Azure Variables'
    - script: |
        cd $(Build.BinariesDirectory)
        rm CMakeCache.txt
        cmake -G Ninja -DDREAM3D_SDK=/Users/Shared/IMF_SDK -DCMAKE_BUILD_TYPE=Release $(Build.Repository.LocalPath)/DREAM3D
      displayName: 'Configure DREAM3D....'
    - script: |
        cd $(Build.BinariesDirectory)
        ctest -D Experimental
      displayName: 'Build DREAM3D and Test DREAM3D with CTest'

      